export const meta = {
  name: 'discovery-devui-hiring-integrations-scale',
  description: 'Heavy discovery for 3 programs: developer-customizable UI framework, 10+ hiring-platform integrations (job boards/sourcing), and 5k-concurrent apply scale (load/stress test + perf hardening). Research + codebase audit + architecture + workflow plan.',
  phases: [
    { title: 'Research', detail: '12 web-research agents (waves of 4): dev-UI, platform APIs, scale' },
    { title: 'Audit', detail: '7 codebase agents (waves): apply path, integration/theme bases, infra' },
    { title: 'Synthesize', detail: '2 agents: architecture + the implementation-workflow plan' },
  ],
}

const RES = { type: "object", additionalProperties: false, properties: {
  topic: { type: "string" },
  findings: { type: "array", items: { type: "object", additionalProperties: false, properties: {
    practice: { type: "string" }, detail: { type: "string", description: "concrete: exact endpoints, auth, partner reqs, libs+versions, data shapes, numbers" }, source: { type: "string" },
  }, required: ["practice", "detail", "source"] } },
  recommendation: { type: "string", description: "concrete plan for OUR stack (Next.js 14 + Express microservices + Prisma/Postgres + BullMQ + NATS + MinIO, Docker)" },
}, required: ["topic", "findings", "recommendation"] };

const AUD = { type: "object", additionalProperties: false, properties: {
  area: { type: "string" }, currentState: { type: "string", description: "how it works now, file:line" },
  reusable: { type: "array", items: { type: "string" } }, gaps: { type: "array", items: { type: "string" } },
  recommendation: { type: "string" },
}, required: ["area", "currentState", "reusable", "gaps", "recommendation"] };

const RCTX = "Senior SaaS architect researcher. USE WebSearch + WebFetch (load via ToolSearch: 'select:WebSearch,WebFetch'). 2026 best practices, cite real URLs, be concrete (exact endpoints, auth flows, partner-program requirements, rate limits, libraries+versions, data shapes). Target: CDC ATS, multi-tenant AI ATS, Next.js 14 (app router, CSS-in-JS + a cd-tokens design-token layer, a module registry + widget registry + brand-ramp already exist), Express 5 microservices, Prisma 7 + Postgres, BullMQ, NATS, MinIO (S3), Docker. It ALREADY has: end-user dashboard customization, a module system, and assessment-provider adapters (HackerRank/HackerEarth/Codility/iMocha/TestGorilla) with AES-GCM-encrypted creds on a TenantIntegration store. END every topic with a concrete recommendation for THIS stack. Honesty: flag partner-gated/credential-required APIs explicitly.";

const ACTX = "Senior engineer auditing the CDC ATS monorepo D:/CDC/ATS (READ-ONLY). Cite file:line. Frontend apps/frontend (Next 14; cd-tokens.css, components/cd/cd-shell.tsx nav, MODULE_REGISTRY in packages/common, lib/widgets registry, lib/theme/brand-ramp.ts, lib/modules). Backend Express services apps/* (job-service owns requisitions/job-postings/public-apply/forms; assessment-service has the provider-adapter pattern; notification-service has TenantIntegration + AES-GCM creds; api-gateway proxies + rate-limits). Public apply: candidate-portal -> gateway /api/public/jobs/:slug/apply-custom -> job-service -> Candidate/Application + resume forward to resume-service. Infra docker-compose.demo.yml (postgres/redis/nats/minio + BullMQ workers). Be precise about the CURRENT state + what to reuse + gaps.";

phase('Research')
log('Research wave 1/3: developer-UI customization')
const research = []
research.push(...(await parallel([
  () => agent(RCTX + "\n\nTOPIC: DEVELOPER-customizable UI frameworks (config-driven, extension points) for a Next.js SaaS — so a DEVELOPER (not an end user) can reskin + restructure the WHOLE app via config/SDK without forking. Research how Backstage, Builder.io, Medusa/Saleor admin, Strapi, Shopify Hydrogen, Refine, and design-system 'config' approaches do it: a typed UI config (theme tokens + nav + routes + copy/i18n + density + logo + feature/surface toggles), a COMPONENT/WIDGET/PAGE registration API, SLOT/override (replace a component) patterns, theme presets, and a developer SDK/plugin model. Give a concrete config schema + registration API + slot system for OUR app (which already has cd-tokens, MODULE_REGISTRY, a widget registry, brand-ramp).", { label: 'r:devui', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: White-label / multi-brand theming + runtime config for developers. Research: design-token config files (Style Dictionary, Tokens Studio), runtime CSS-variable theming, per-deployment/per-tenant config, theme presets + dark/light, fluid type/space config, logo/favicon/font config, and how to expose ALL of it as a single developer-editable config (file + env + admin override) with type safety + validation. Concrete recommendation for extending our cd-tokens + brand-ramp into a full developer theming config.", { label: 'r:theming-config', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: Plugin / extension architecture for a developer-customizable app — registering custom pages/routes, nav items, widgets, dashboard tiles, and component overrides at build-time and (optionally) runtime; a manifest/plugin API; safe extension points; how this layers on an existing MODULE_REGISTRY + widget registry. Give the registration API + manifest schema + how a developer adds a custom widget/page/nav entry without editing core.", { label: 'r:plugin-ext', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: Job-board / hiring-platform integration PATTERNS (the shared abstraction across 10+ platforms). Research the common integration shapes: (a) JOB POSTING (programmatic API vs XML/JSON job FEED, e.g. the indexable feed model), (b) APPLY INGEST (Indeed Apply, Apply-with-LinkedIn, board-hosted apply -> webhook/postback into the ATS), (c) CANDIDATE SOURCING/SEARCH-IMPORT, (d) status/analytics sync. Auth models (OAuth2 partner apps vs API keys vs feed URLs), partner-program gating reality, and a unified HiringPlatformProvider adapter interface (postJob/closeJob/fetchApplications/searchCandidates/verifyWebhook/parseApplication -> normalized). Recommend the interface + the normalized job + application shapes for our stack.", { label: 'r:board-patterns', phase: 'Research', schema: RES }),
])).filter(Boolean))
log('Research wave 2/3: platform APIs (the 10+)')
research.push(...(await parallel([
  () => agent(RCTX + "\n\nTOPIC: LinkedIn hiring integrations (the big one). Research LinkedIn Talent Solutions: Job Posting API, Apply Connect / Apply with LinkedIn (apply-ingest), Recruiter System Connect (RSC), profile/sourcing access, and the Share/Jobs APIs. EXACT endpoints, OAuth scopes, the partner-program/approval requirements (what is gated), rate limits, and the apply-postback shape. Be explicit about what needs LinkedIn partner approval vs what is self-serve. Concrete adapter plan (postJob, apply ingest webhook, normalized application).", { label: 'r:linkedin', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: Indian + global job boards: Naukri ('Nowcree'), Foundit/Monster, Shine, plus Indeed and ZipRecruiter. For EACH: job posting API / feed, apply ingest, candidate search/Resdex sourcing, auth (API key/OAuth/partner), rate limits, partner requirements. Indeed: XML feed + Indeed Apply + Sponsored Jobs API. ZipRecruiter: partner job API. Give per-platform adapter specifics (endpoints + auth + apply postback).", { label: 'r:naukri-indeed', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: More boards: Glassdoor, SEEK (AU/NZ), Dice (tech), Wellfound/AngelList Talent, Stack Overflow Talent/Jobs. For EACH: posting/feed API, apply ingest, sourcing, auth + partner reqs + rate limits. Per-platform adapter specifics. Note which are deprecated/merged (e.g. SO Jobs) and the current alternative.", { label: 'r:boards-2', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: Aggregators + open/standard channels: Google for Jobs (schema.org JobPosting structured data + indexing API + the third-party-no-direct-API reality), Adzuna, Jooble, Jobg8/job-XML standards (HR-XML/HROpen, the 'job feed' XML schema many boards consume), and a generic JOB-FEED publisher (one XML/JSON feed many boards ingest). Give the JobPosting structured-data shape + a generic feed format we can emit to cover many boards at once.", { label: 'r:aggregators-feed', phase: 'Research', schema: RES }),
])).filter(Boolean))
log('Research wave 3/3: scale + load testing')
research.push(...(await parallel([
  () => agent(RCTX + "\n\nTOPIC: Load/stress testing a public form-submit (apply) endpoint at 5,000+ concurrent users. Compare k6 vs Artillery vs Locust vs autocannon for this (pick one for a Node/Docker stack), how to model 5k concurrent virtual users + ramp + sustained, multipart/file-upload load, the metrics to capture (throughput RPS, p95/p99 latency, error rate, saturation), and how to run it against a local Docker stack + interpret single-host limits vs production. Give a concrete k6 (or chosen tool) script outline + thresholds for the apply flow.", { label: 'r:loadtest', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: High-concurrency apply-INGESTION architecture (absorb 5k concurrent form submits without falling over). The accept-fast + async pattern: validate + persist minimal + enqueue (BullMQ) + 202 Accepted, doing heavy work (resume parse, screening, board postback) async; idempotency keys; backpressure + queue depth; rate limiting that protects without rejecting legit bursts; DB connection pooling (pgbouncer) + Prisma pool sizing; horizontal scaling of the public ingest service; Postgres write throughput for bursts. Give the concrete re-architecture of a /apply endpoint to sustain 5k concurrent on our Express+Prisma+BullMQ+Postgres stack.", { label: 'r:ingest-arch', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: File/resume UPLOAD at scale. The bottleneck of multipart uploads THROUGH an API service; presigned direct-to-object-storage uploads (S3/MinIO presigned PUT/POST) so the API never streams the file; client-direct upload + a key reference in the apply payload; async virus-scan/parse from the object store; size/type limits; CDN/edge for the static apply form. Give the presigned-upload flow for our MinIO + how the apply form posts the file key instead of the bytes.", { label: 'r:upload-scale', phase: 'Research', schema: RES }),
  () => agent(RCTX + "\n\nTOPIC: Benchmark how leading ATSes do (a) job DISTRIBUTION to many boards (one-click multi-post, job feeds, the 'post to 100s of boards' model like Greenhouse/Lever job board integrations + programmatic vendors like VONQ/Joveo/Appcast), and (b) high-volume APPLY at scale (career-site apply spikes, queueing, anti-bot). 3-5 concrete architectural moves to emulate for our multi-board distribution + 5k-concurrent apply.", { label: 'r:bench-distribution', phase: 'Research', schema: RES }),
])).filter(Boolean))
log('Research done: ' + research.length + '/12')

phase('Audit')
log('Audit wave 1: apply path, integration base, theme/module base')
const audit = []
audit.push(...(await parallel([
  () => agent(ACTX + "\n\nAREA: PUBLIC APPLY PATH end-to-end (the 5k-concurrent target). Trace candidate-portal apply page -> gateway /api/public/jobs/:slug/apply-custom -> job-service handler -> Candidate/Application create -> resume forward to resume-service -> parse/screen. List EVERY synchronous step, the multer/file handling, DB writes, external calls, and the express.json/rate-limit middleware on the path. Identify the exact bottlenecks for 5k concurrent + which steps can move async. Cite file:line.", { label: 'a:apply', phase: 'Audit', schema: AUD }),
  () => agent(ACTX + "\n\nAREA: INTEGRATION FRAMEWORK (base for hiring-platform adapters). Read notification-service TenantIntegration + the WF8 assessment-service provider adapters (src/providers/*, the AssessmentProvider interface, the AES-GCM creds via @cdc-ats/common, the inbound webhook + poll reconciler + outbound worker pattern). Determine exactly what to REUSE for a HiringPlatformProvider adapter family (interface, creds store, outbound worker, inbound webhook, poll) and what is net-new. Cite file:line.", { label: 'a:integ', phase: 'Audit', schema: AUD }),
  () => agent(ACTX + "\n\nAREA: THEME + MODULE + WIDGET + NAV systems (base for the developer-UI customization). Read cd-tokens.css, lib/theme/brand-ramp.ts, the MODULE_REGISTRY (packages/common/src/modules), lib/widgets (registry/sources/schema/defaults), lib/modules/registry.ts, cd-shell.tsx nav definition + how routes/nav/theme are declared today. Determine how to add a DEVELOPER UI-config layer (single typed config controlling theme/nav/copy/density/surfaces + a component/widget/page registration + slot overrides) on top of these. Cite file:line + the extension points.", { label: 'a:theme-mod', phase: 'Audit', schema: AUD }),
])).filter(Boolean))
log('Audit wave 2: job-service, gateway/perf, infra')
audit.push(...(await parallel([
  () => agent(ACTX + "\n\nAREA: JOB-SERVICE (owns posting + apply + forms; where job DISTRIBUTION lives). Read job-service requisitions/job-postings/public routes + the form builder + the JobPosting model. Determine where to add multi-board job DISTRIBUTION (post a requisition to N hiring platforms + ingest applies back) + the JobPosting->board mapping + status sync. What models/routes/workers are net-new. Cite file:line.", { label: 'a:job', phase: 'Audit', schema: AUD }),
  () => agent(ACTX + "\n\nAREA: GATEWAY + PERF on the apply path. Read api-gateway rate limiting (the rateLimit config), the proxy for /api/public/*, express.json vs streaming for multipart, body size limits, and any timeouts/pooling. Identify perf levers + what blocks 5k concurrent at the gateway. Also the Prisma client pool config + Postgres max_connections in compose. Cite file:line.", { label: 'a:gateway-perf', phase: 'Audit', schema: AUD }),
  () => agent(ACTX + "\n\nAREA: INFRA + scaling levers. Read docker-compose.demo.yml service resource limits/replicas, postgres/redis/nats/minio config, the BullMQ worker setup (queues, concurrency), MinIO usage (is it used for resumes? presigned?). Determine the scaling levers for a 5k-concurrent load test (replicas, pooling, queue concurrency, minio presigned) + what a single-host local test can realistically show vs production. Cite file:line.", { label: 'a:infra', phase: 'Audit', schema: AUD }),
])).filter(Boolean))
log('Audit wave 3: frontend config/nav/routing for dev-UI')
audit.push(...(await parallel([
  () => agent(ACTX + "\n\nAREA: FRONTEND config/nav/routing/copy structure (for the developer-UI customization layer). How are nav items, routes, page titles, copy/labels, theme defaults, and feature visibility DECLARED today (cd-shell NAV array, app router pages, hardcoded strings, cd-tokens)? Determine what a single developer config would need to override to customize the WHOLE UI (theme, nav order/labels/icons, route enablement, copy/i18n, density, logo, default dashboards) + how to wire a config provider + slot/override registry without breaking existing screens. Cite file:line.", { label: 'a:fe-config', phase: 'Audit', schema: AUD }),
])).filter(Boolean))
log('Audit done: ' + audit.length + '/7')

phase('Synthesize')
const arch = await agent("Lead architect. Using ONLY these findings + audit (cite sources/files), produce the ARCHITECTURE for 3 programs on the CDC ATS (Next 14 + Express microservices + Prisma/Postgres + BullMQ + NATS + MinIO, static Docker images). RESEARCH:\n" + JSON.stringify(research) + "\n\nAUDIT:\n" + JSON.stringify(audit) + "\n\nProduce concretely: (1) DEVELOPER-UI CUSTOMIZATION: the typed UI-config schema (theme/nav/copy/density/surfaces/logo), the component/widget/page registration API, the slot/override system, the config provider + validation, and the developer docs/SDK surface; exact files. (2) HIRING-PLATFORM INTEGRATIONS: the HiringPlatformProvider adapter interface + normalized job/application shapes, the 10+ target platforms grouped by integration type (programmatic API vs job-feed vs apply-ingest) with per-platform auth + partner-gating honesty, the owning service (extend job-service vs new distribution-service), creds (reuse AES-GCM TenantIntegration), outbound post + inbound apply-webhook + poll, module gating, and a generic JobPosting structured-data/XML FEED that covers many boards at once. (3) SCALE: the re-architected 5k-concurrent apply path (accept-fast + BullMQ async + presigned MinIO upload + pooling + tuned rate limit + idempotency), and the load/stress test harness (tool + script + thresholds) + how to run it against the local stack honestly. Give exact Prisma models, routes, workers, frontend files, npm deps per program.",
  { label: 's:arch', phase: 'Synthesize', schema: { type: "object", additionalProperties: false, properties: {
    devUiArchitecture: { type: "string" }, hiringIntegrationsArchitecture: { type: "string" }, scaleArchitecture: { type: "string" },
    platforms: { type: "array", items: { type: "object", additionalProperties: false, properties: { name: { type: "string" }, integrationType: { type: "string" }, auth: { type: "string" }, partnerGated: { type: "boolean" }, notes: { type: "string" } }, required: ["name", "integrationType", "auth", "partnerGated", "notes"] } },
    prismaModels: { type: "array", items: { type: "string" } }, apiContracts: { type: "array", items: { type: "string" } }, frontendFiles: { type: "array", items: { type: "string" } }, newDependencies: { type: "array", items: { type: "string" } }, openRisks: { type: "array", items: { type: "string" } },
  }, required: ["devUiArchitecture", "hiringIntegrationsArchitecture", "scaleArchitecture", "platforms", "prismaModels", "apiContracts", "frontendFiles", "newDependencies", "openRisks"] } })

const plan = await agent("Using the architecture, produce the IMPLEMENTATION BUILD PLAN as a sequence of structured workflows (each with disjoint-file agent slices + a verify phase) to ship all 3 programs production-ready, ADDITIVE + backward-compatible (frozen v1 demo unaffected; new surfaces module-gated). Architecture:\n" + JSON.stringify(arch) + "\n\nFor EACH workflow: name, goal, agent slices (disjoint files), dependencies, verification (per-service tsc + no-fabrication + the load-test run), and the Docker deploy/migration notes (reuse the migrator-rebuild recipe; new workspace pkgs need both Dockerfiles' COPY + nested-node_modules; frontend value-imports need the dep declared). Order by dependency. Group the 10+ platform adapters into parallel-agent workflows (one agent per adapter) for efficiency rather than serial. Include the load/stress-test workflow that BUILDS the harness, hardens the apply path, RUNS the test, and reports real numbers.",
  { label: 's:plan', phase: 'Synthesize', schema: { type: "object", additionalProperties: false, properties: {
    workflows: { type: "array", items: { type: "object", additionalProperties: false, properties: { name: { type: "string" }, goal: { type: "string" }, slices: { type: "array", items: { type: "string" } }, dependencies: { type: "string" }, verification: { type: "string" } }, required: ["name", "goal", "slices", "dependencies", "verification"] } },
    sequencing: { type: "string" }, deployNotes: { type: "string" },
  }, required: ["workflows", "sequencing", "deployNotes"] } })

return { research, audit, arch, plan }
