export const meta = {
  name: 'sourcing-ai-and-robustness-fixes',
  description: 'Real Groq sourcing agent + ZodError 500 robustness + career-portal posting flow + team chat + empty-space, wired end to end',
  phases: [
    { title: 'Backend', detail: '5 agents fix disjoint services (common, candidate, job, notification, gateway)' },
    { title: 'Frontend', detail: 'wire sourcing page to the real agent + portal real-time + chat + layout' },
    { title: 'Verify', detail: 'per-service builds + flow/contract/no-fabrication audit' },
  ],
}

const REPORT = {
  type: "object", additionalProperties: false,
  properties: {
    files: { type: "array", items: { type: "string" } },
    summary: { type: "string" },
    buildClean: { type: "boolean" },
    contractNotes: { type: "string", description: "exact endpoint paths / request+response shapes / behavior you implemented, for cross-agent alignment" },
    notes: { type: "string" },
  },
  required: ["files", "summary", "buildClean", "contractNotes", "notes"],
}

const CTX = [
  "Repo D:/CDC/ATS — multi-tenant AI ATS. TypeScript, Express 5, Prisma 7, Postgres, BullMQ, NATS; static Docker images (docker-compose.demo.yml). Investigate the ACTUAL code first (read/grep), then fix, citing file:line. HARD RULE: NO mock/sample/demo/fabricated data anywhere — only real data from the real DB / real LLM, or honest empty states. Match existing code idioms + error handling. Build/typecheck your own service before finishing.",
  "AI/LLM: the repo calls LLMs via its ai-engine (OpenRouter, routes to Groq models for some agents; the candidate-screener already does real LLM calls). Use the SAME real LLM client the existing agents use — do NOT invent a new provider, do NOT stub. 'Groq/croq API' = the Groq models behind the ai-engine.",
].join("\n");

phase('Backend')
log('5 backend agents: common(ZodError) / candidate(sourcing AI) / job(portal) / notification(chat) / gateway...')
const backend = (await parallel([
  () => agent(CTX + "\n\n=== SLICE: packages/common — robust error handling ===\nBUG: job-service returns HTTP 500 (Unhandled error) when a request body fails Zod validation (e.g. POST /internal/requisitions or /internal/jd-author with missing title/department/location). Read packages/common/src/middleware/error-handler.ts — its ZodError branch is not catching these (they fall through to the generic 500). Make it robustly map ANY ZodError (check both `err instanceof ZodError` AND `err?.name === 'ZodError'` AND presence of `err.issues`) to HTTP 400 with a clean { success:false, error:{ code:'VALIDATION_ERROR', message, details: issues } } envelope. Also confirm a thrown AppError/Errors.* with a `.status` is honored. Do not change unrelated behavior. Build: cd packages/common && npm run build (this is bundled into every service's dist; the orchestrator will rebuild the dependent services). Report the exact condition you used.", { label: 'be:common', phase: 'Backend', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE: candidate-service — REAL Groq sourcing agent ===\nThe /sourcing page button must trigger a REAL AI candidate search. Read apps/candidate-service/src/routes/agent-sourcing.ts + src/lib/sourcing-tools.ts + how candidate-screener calls the LLM. Implement/strengthen a POST endpoint (keep/extend the existing one; e.g. POST /internal/sourcing/search or the agent-sourcing route) that: (1) takes { query: string, limit?: number } (a free-text 'who I need' description); (2) loads the tenant's REAL Candidate rows from the DB (with their parsed resume text / skills / role / score — the knowledge base) — tenant-scoped; (3) ranks them by fit to the query using the REAL LLM (Groq via the ai-engine, same client the screener uses) and returns, for each top match, { candidateId, name, role, score (0-100 fit), evidence (1-2 sentence justification grounded in the candidate's real data) }; (4) returns honest empty when the tenant has no candidates. NO fabricated candidates — only real rows. If the LLM is unavailable, fall back to a real keyword/skill match over the real rows (still real data), never invented people. Build: cd apps/candidate-service && npm run build (or npx tsc --noEmit). In contractNotes give the EXACT path + request + response JSON shape so the frontend can wire to it.", { label: 'be:candidate-sourcing', phase: 'Backend', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE: job-service — career-portal posting flow ===\nTwo bugs: (A) GET /job-postings ignores the ?requisitionId= query (returns all tenant postings) so the frontend's findPostingForRequisition wrongly matches the seed posting -> every requisition's 'Post job' link is the same static seed slug. FIX: in apps/job-service/src/routes/job-postings.ts GET '/', when req.query.requisitionId is present, filter where { tenantId, requisitionId }. (B) The career portal only shows 1 job because only 1 JobPosting is published; there are 13 OPEN requisitions with none. FIX: add an idempotent helper that ensures a published JobPosting exists for a requisition (slug = slugify(title)+'-'+short stable suffix, unique; isPublished true; publishedAt now; one per requisitionId), and call it (best-effort, never failing the main op) when a requisition is created with status OPEN and when a requisition's status changes to OPEN (read apps/job-service/src/routes/requisitions.ts create + status-update handlers). Also add POST /job-postings/backfill-open (requirePublisher) that creates postings for all the caller-tenant's OPEN requisitions lacking one (idempotent) so existing reqs appear — the orchestrator will call it once. Keep slugs per-requisition (never reuse 'senior-ml-engineer'). Build: cd apps/job-service && npm run build. contractNotes: the filter, the helper, the backfill route + response.", { label: 'be:job-portal', phase: 'Backend', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE: notification-service — team chat 'truncated & empty' ===\nThe /chat page lists conversations (previews 'hi'/'hii') but the main panel stays empty after selecting one, and messages look truncated. Read apps/notification-service/src/routes (the messages/chat router — list conversations, get thread, send) and how the frontend fetches a thread (apps/frontend/app/(dashboard)/chat or /chat page + hooks/use-notifications or lib). Determine why selecting a conversation does not load its messages (GET thread returning empty/erroring, wrong id, RLS, or SSE) and FIX the backend so GET thread returns the real messages for that conversation (tenant-scoped, ordered). If messages are genuinely only 'hi'/'hii', that is real data (fine) — focus on the empty MAIN PANEL not loading the thread. Build: cd apps/notification-service && npm run build. contractNotes: the thread endpoint path + response shape.", { label: 'be:chat', phase: 'Backend', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE: api-gateway — sourcing + validation passthrough ===\nEnsure POST /api/sourcing/search (and the sourcing routes) proxy to candidate-service with auth + the requireAgentPlan('sourcing') gate, and that JSON request bodies reach candidate-service (check how other JSON POSTs are forwarded — express.json vs streaming proxy; the sourcing route must receive the { query } body). Read apps/api-gateway/src/app.ts for the /api/sourcing wiring; fix if the sourcing search route is missing or drops the body. Do NOT change unrelated routes. Build: cd apps/api-gateway && npm run build. contractNotes: the exact /api/sourcing/* -> candidate-service mapping.", { label: 'be:gateway', phase: 'Backend', schema: REPORT }),
])).filter(Boolean)
log('Backend done: ' + backend.length + '/5; contracts gathered')

phase('Frontend')
const fe = await agent(CTX + "\n\n=== SLICE: FRONTEND (apps/frontend) — wire everything the backend just exposed ===\nThe backend agents just implemented these (read their actual routes to get exact shapes): real sourcing search, job-postings requisitionId filter + backfill, chat thread endpoint. Implement ALL of the following, real-data-only, theme-adaptive, responsive, honest loading/empty/error, no fabricated data:\n1) SOURCING (apps/frontend/app/(dashboard)/sourcing/page.tsx): it is currently a STATIC stub — the 'Find candidates' button has no onClick. Make it a client component: on submit POST the typed query to the real sourcing endpoint (read candidate-service route / gateway mapping the backend agent reported, e.g. POST /api/sourcing/search { query }), show a loading state, then render the REAL ranked candidate matches (name, role, fit score, evidence) in result cards that FILL the current empty space; honest empty ('no matches'/'add candidates first') and error states. Add the fetcher to lib/api or lib/api-client as appropriate. NO sample results.\n2) CAREER-PORTAL FLOW: in lib/api fix findPostingForRequisition to return `list.find(p => p.requisitionId === requisitionId) ?? null` (drop the `?? list[0]` fallback that returns the seed). Make the public career portal listings real-time/refresh: app/(candidate-portal)/jobs/page.tsx and app/(candidate-portal)/c/[slug]/jobs/page.tsx should re-fetch /public/jobs periodically (~30s) + on focus so newly posted roles appear, and render ALL returned roles (no artificial cap hiding them).\n3) TEAM CHAT (the /chat page): fix selecting a conversation so the main panel loads + shows the real thread (wire to the thread endpoint the chat backend agent reported), fix truncated previews if they hide real text, and fill the empty main-panel space with the real conversation.\n4) EMPTY SPACE: the sourcing page's large empty area is filled by the results (item 1); also fix any other obvious empty-space/layout imbalance on these pages (use the responsive idioms already in the app).\nBuild: cd apps/frontend && npx tsc --noEmit must pass. Report each wired endpoint in contractNotes.", { label: 'fe:wire-all', phase: 'Frontend', schema: REPORT })

phase('Verify')
const verify = (await parallel([
  () => agent("Build verification for D:/CDC/ATS. Run verbatim and report each: cd packages/common && npm run build ; cd apps/candidate-service && npx tsc --noEmit ; cd apps/job-service && npx tsc --noEmit ; cd apps/notification-service && npx tsc --noEmit ; cd apps/api-gateway && npx tsc --noEmit ; cd apps/frontend && npx tsc --noEmit . Return REPORT: files=problem files, summary=overall pass/fail, buildClean=all green, contractNotes='', notes=every error verbatim.", { label: 'vf:builds', phase: 'Verify', schema: REPORT }),
  () => agent(CTX + "\n\n=== AUDIT: flow + no-fabrication ===\nVerify, citing file:line: (1) the sourcing search path is end-to-end real — frontend posts the query to the real candidate-service endpoint which ranks REAL Candidate rows via the real LLM (Groq) with evidence; NO hardcoded/sample candidate results anywhere in sourcing/page.tsx or the route. (2) error-handler maps ZodError -> 400 (so requisitions/jd-author bad bodies are 400 not 500). (3) job-service GET /job-postings filters by requisitionId, auto-publish + backfill create per-requisition slugs (not the seed), and the frontend findPostingForRequisition no longer falls back to list[0]. (4) chat thread endpoint returns real messages and the frontend loads them on select. (5) no new mock/sample/demo data introduced in any edited file. Return REPORT: files=violation files, summary=verdict, buildClean=true if no fabrication/contract breaks, contractNotes=verified flows, notes=each issue with file:line.", { label: 'vf:audit', phase: 'Verify', schema: REPORT }),
])).filter(Boolean)

return { backend, frontend: fe, verify }
