export const meta = {
  name: 'wf3-schema-rls-assessment-bootstrap-source',
  description: 'WF3 (SOURCE-ONLY, Docker is down): all Prisma schema additions + RLS + assessment-service bootstrap + plan-limits adoption, with prisma generate + host tsc. NO docker / NO db-push here (deferred to the migrator-rebuild recipe once the daemon is healthy).',
  phases: [
    { title: 'Schema', detail: '4 agents: billing, identity, tenant schema+RLS, assessment-service bootstrap (disjoint services)' },
    { title: 'Adopt', detail: '1 agent: replace the 3 PLAN_LIMITS copies with the derived import + build affected services' },
    { title: 'Verify', detail: 'host tsc sweep + backward-compat/no-fabrication audit (DB-apply deferred)' },
  ],
}

const REPORT = {
  type: "object", additionalProperties: false,
  properties: {
    files: { type: "array", items: { type: "string" } },
    summary: { type: "string" },
    buildClean: { type: "boolean" },
    contract: { type: "string", description: "exact new models/fields + RLS policy names for the migration recipe + later WFs" },
    notes: { type: "string" },
  },
  required: ["files", "summary", "buildClean", "contract", "notes"],
}

const CTX = "Repo D:/CDC/ATS — multi-tenant AI ATS, Prisma 7 + Postgres, DB-per-service with RLS. CRITICAL: the Docker daemon is DOWN right now — do NOT run ANY docker command and do NOT attempt db push / prisma migrate deploy (those are deferred to a manual recipe). You MAY run `npx prisma generate --schema apps/<svc>/prisma/schema.prisma` (local, no daemon) and `npm run build --workspace=@cdc-ats/<svc>` (host tsc). READ the real files first: the target service's prisma/schema.prisma, its prisma/apply-rls.ts (the idempotent RLS applier with its TENANT_TABLES list + tenant_isolation policy pattern), its src/lib/prisma.ts (two-client: prisma=RLS via <SVC>_APP_DATABASE_URL + prismaAdmin), and how an existing service is structured. HARD RULES: every schema change ADDITIVE (new tables / new defaulted columns) so the frozen v1 demo cannot regress; follow the EXACT RLS idiom already in that service; no mock/fabricated data; no em/en dashes; this repo TRACKS generated prisma clients so commit the regenerated client. @cdc-ats/common (WF1) now exports modules/registry, modules/plan-limits (derivePlanLimits/PLAN_LIMITS), crypto/aes-gcm, validation/ajv; @cdc-ats/contracts exports assessment/dashboard/module DTOs. Rebuild common+contracts dist is already done. This is WF3 of a 10-workflow enterprise build.";

phase('Schema')
log('4 schema agents (disjoint services)')
const schema = (await parallel([
  () => agent(CTX + "\n\n=== SLICE C1: billing-service — ModuleRegistry + TenantModule ===\nEDIT apps/billing-service/prisma/schema.prisma: add ModuleRegistry (id, key @unique, name, version, category, type, requiresPlan String?, manifest Json, defaultEnabled Boolean @default(false), createdAt) as a PLATFORM-GLOBAL table (no tenantId — like the existing PlatformAgentKillSwitch); add TenantModule (id, tenantId, moduleKey, enabled Boolean @default(false), config Json @default(\"{}\"), enabledAt DateTime?, updatedBy String, @@unique([tenantId,moduleKey]), @@index([tenantId])) as a sibling of the dormant FeatureFlag. EDIT apps/billing-service/prisma/apply-rls.ts: add TenantModule to TENANT_TABLES (gets the standard tenant_isolation policy); leave ModuleRegistry un-RLS'd (platform-global, read via prismaAdmin) exactly like PlatformAgentKillSwitch. Then `npx prisma generate --schema apps/billing-service/prisma/schema.prisma` + `npm run build --workspace=@cdc-ats/billing-service`. NO docker, NO db push. In `contract` give the exact model fields + which RLS policy each gets.", { label: 'c1:billing', phase: 'Schema', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE C2: identity-service — DashboardLayout + UserUiPrefs ===\nEDIT apps/identity-service/prisma/schema.prisma: add DashboardLayout (id, tenantId, userId String? (NULL = tenant-default/system row), scope String, dashboardKey String @default(\"home\"), name String, document Json, schemaVersion Int @default(1), isDefault Boolean @default(false), updatedBy String, createdAt, updatedAt, @@unique([tenantId,userId,dashboardKey]), @@index([tenantId,scope])) and UserUiPrefs (id, tenantId, userId String @unique, colorMode String @default(\"system\"), density String @default(\"comfortable\"), locale String?, timezone String?, accentOverride String?, prefs Json @default(\"{}\"), updatedAt, @@index([tenantId])). EDIT apps/identity-service/prisma/apply-rls.ts: add BOTH to its RLS table list with tenant_isolation on tenantId. identity is cross-tenant-heavy and uses the OPT-IN prismaRls pattern — ensure these tables work with prismaRls (the per-user routers will use it in WF6); login/saga/super-admin/invite stay on admin. Then `npx prisma generate --schema apps/identity-service/prisma/schema.prisma` + `npm run build --workspace=@cdc-ats/identity-service`. NO docker. In `contract` give fields + policy.", { label: 'c2:identity', phase: 'Schema', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE C3: tenant-service — dashboard/theme columns ===\nEDIT apps/tenant-service/prisma/schema.prisma: add to the existing Tenant model (additive, defaulted): dashboardThemeTokens Json @default(\"{}\"), defaultColorMode String @default(\"system\"), defaultDashboardByRole Json @default(\"{}\"). (embedAllowedOrigins was already added in WF2 — do not duplicate it.) Then `npx prisma generate --schema apps/tenant-service/prisma/schema.prisma` + `npm run build --workspace=@cdc-ats/tenant-service`. The Tenant RLS policy is already keyed on id; no apply-rls change needed for added columns. EDIT the tenant branding self-service router to accept+persist defaultColorMode + dashboardThemeTokens (validate shape) on the branding PUT (additive, optional), like WF2 did for embedAllowedOrigins. NO docker. In `contract` give the new fields.", { label: 'c3:tenant', phase: 'Schema', schema: REPORT }),

  () => agent(CTX + "\n\n=== SLICE C4: NEW assessment-service bootstrap (skeleton only) ===\nCreate apps/assessment-service as a NEW Express 5 microservice SKELETON modeled EXACTLY on an existing service (clone job-service's structure: package.json name @cdc-ats/assessment-service, tsconfig, src/index.ts Express boot with ONLY a /healthz route + readAuthHeaders wiring, src/lib/prisma.ts two-client (prisma=RLS via ASSESSMENT_APP_DATABASE_URL + prismaAdmin via ASSESSMENT_DATABASE_URL), src/lib/logger, port 4014). Create prisma/schema.prisma with ALL the OA models: Assessment, AssessmentInvite (tokenHash @unique, providerInvitationId String? @unique), Attempt (@unique inviteId), Answer (@@unique([attemptId,questionId])), ProctorEvent, AssessmentResult, and QuestionBank + Question (Question with type enum MCQ_SINGLE|MCQ_MULTI|TRUE_FALSE|SHORT_ANSWER|ESSAY|CODING) — use the EXACT field sets from the architecture (read packages/contracts/src/dtos/assessment.ts for the shapes). Create prisma/apply-rls.ts (clone the job-service idempotent applier): strict tenant_isolation on Assessment/AssessmentInvite/Attempt/Answer/ProctorEvent/AssessmentResult; QuestionBank/Question use the job-service Skill NULLABLE-global policy (tenantId IS NULL OR =current_setting). EDIT infra/postgres-init.sql add `CREATE DATABASE assessment_db;` (idempotent style matching the others). EDIT .env (gitignored) add ASSESSMENT_DATABASE_URL + ASSESSMENT_APP_DATABASE_URL (postgres on the demo host). EDIT .env.example (tracked) document both. EDIT docker-compose.demo.yml add the assessment-service service (port 4014, networks [ats_net], env incl ASSESSMENT_* + ATS_CONFIG_ENC_KEY + NATS/REDIS) AND a Judge0 CE sidecar PLACEHOLDER (image judge0/judge0:1.13.1, on its OWN separate network with NO route to ats_net, ALLOW_ENABLE_NETWORK=false, commented as UNROUTED until WF7) — present but the gateway does NOT proxy to assessment yet (that is WF7). Run `npx prisma generate --schema apps/assessment-service/prisma/schema.prisma` + `npm run build --workspace=@cdc-ats/assessment-service` (add it to the workspace; npm install if needed for prisma client). NO docker run / NO db push. In `contract` give every model + field + RLS policy + the new env vars + the compose service name.", { label: 'c4:assessment', phase: 'Schema', schema: REPORT }),
])).filter(Boolean)
log('Schema done: ' + schema.length + '/4')

phase('Adopt')
log('Adopt derived PLAN_LIMITS across the 3 copies + build affected services')
const adopt = await agent(CTX + "\n\n=== SLICE C5: adopt derived PLAN_LIMITS (pure refactor) ===\nThe 3 in-service PLAN_LIMITS copies (grep PLAN_LIMITS across apps/billing-service, apps/job-service service-client, apps/identity-service) must now import the SINGLE derived object from @cdc-ats/common (WF1 added modules/plan-limits exporting PLAN_LIMITS/derivePlanLimits). Replace each local copy with the import; assert (in a comment) the FREE/STARTER/PROFESSIONAL/ENTERPRISE values are byte-equal to what each service had (no entitlement change — this must not alter any gating). Do NOT change call sites' behavior. Then host-build each touched service: `npm run build --workspace=@cdc-ats/billing-service`, `--workspace=@cdc-ats/job-service`, `--workspace=@cdc-ats/identity-service` and confirm tsc clean. NO docker. In `contract` confirm the values are unchanged and list the files edited.", { label: 'c5:adopt', phase: 'Adopt', schema: REPORT })
log('Adopt done: buildClean=' + (adopt && adopt.buildClean))

phase('Verify')
const verify = (await parallel([
  () => agent("Host build verification for D:/CDC/ATS (Docker is DOWN — do NOT use docker; host tsc only). Run verbatim and report each: npm run build --workspace=@cdc-ats/common ; npm run build --workspace=@cdc-ats/contracts ; npm run build --workspace=@cdc-ats/billing-service ; npm run build --workspace=@cdc-ats/identity-service ; npm run build --workspace=@cdc-ats/tenant-service ; npm run build --workspace=@cdc-ats/job-service ; npm run build --workspace=@cdc-ats/assessment-service. REPORT: files=any with errors, summary=pass/fail, buildClean=all green, contract='', notes=every error verbatim.", { label: 'vf:build', phase: 'Verify', schema: REPORT }),
  () => agent(CTX + "\n\n=== AUDIT: backward-compat + no-fabrication (read-only, no docker) ===\nVerify citing file:line: (1) all schema additions are ADDITIVE (new tables / new DEFAULTED columns) — no existing column removed/renamed/made-required, so the frozen v1 schema is a strict subset. (2) each new table is added to its service's apply-rls.ts with the correct policy (tenant_isolation for tenant-scoped; NULLABLE-global for QuestionBank/Question; ModuleRegistry left platform-global). (3) the derived PLAN_LIMITS adoption did NOT change any FREE/PROFESSIONAL/ENTERPRISE value (entitlement parity). (4) assessment-service is bootstrapped but UNROUTED (gateway has no /api/assessments proxy yet) and its compose entry + Judge0 sidecar are isolated. (5) NO mock/fabricated/seed rows added. (6) the regenerated prisma clients are present (repo tracks generated/). Return REPORT: files=violations, summary=verdict, buildClean=true iff clean, contract='the exact db-push/migrator-rebuild recipe inputs: list every service whose schema changed + every new env var + the new database', notes=each issue with file:line.", { label: 'vf:audit', phase: 'Verify', schema: REPORT }),
])).filter(Boolean)

return { schema, adopt, verify }
