export const meta = {
  name: 'wfi-scale-apply-and-loadtest',
  description: 'WF-I: re-architect the public apply path to accept-fast 202 + idempotency + presigned-MinIO upload + staged BullMQ pipeline (BACKWARD-COMPATIBLE: keep the existing multipart path working), fix the gateway trust-proxy/rate-limit IP-collapse + keep-alive/timeouts, add per-board credential cards, and build the k6 load/stress harness. Write-only; orchestrator builds + runs the test.',
  phases: [
    { title: 'Edge', detail: 'presigned route + gateway trust-proxy/rate-limit fix + k6 harness + cred cards (disjoint)' },
    { title: 'Pipeline', detail: 'accept-fast apply (both paths) + async workers + status route + frontend 2-step + infra tuning' },
  ],
}

const REPORT = { type: "object", additionalProperties: false, properties: {
  files: { type: "array", items: { type: "string" } }, summary: { type: "string" }, contract: { type: "string" }, notes: { type: "string" },
}, required: ["files", "summary", "contract", "notes"] };

const CTX = "Repo D:/CDC/ATS. EXECUTION RULE: write SOURCE ONLY — no npm/npx/tsc/prisma/docker (orchestrator builds + runs the load test; those pop a Windows dialog here). NodeNext ESM (.js imports). READ FIRST: apps/job-service/src/routes/public.ts (the CURRENT apply-custom: multer multipart -> dedupe Candidate by (tenantId,email) -> create Application -> forward resume to resume-service; this is on prismaAdmin), apps/job-service/prisma/schema.prisma (ApplicationIdempotency model already added in WF-E), apps/resume-service/src/lib/storage.ts (the S3/MinIO client + buildKey + presigned-download), the BullMQ worker pattern (assessment/job workers), apps/api-gateway/src/app.ts (the rateLimit config + ioredis ~54 + forwardHeaders + the public proxy) + index.ts (server setup), apps/job-service/src/lib/service-client.ts (forwardResumeUpload + callCandidateService ~60,84), docs/LOAD_TESTING.md if present. HARD RULES (CRITICAL for not breaking the frozen v1 + current v2 demo): the public apply endpoint MUST stay BACKWARD-COMPATIBLE — if the request is the EXISTING multipart upload, keep the CURRENT behavior working unchanged (old frontends still apply); the NEW accept-fast path (presigned objectKey -> 202) is an ADDITIVE alternative the new frontend uses. NO fabricated data (no synthetic 201 before the row exists; status reflects the real pipeline stage). ClamAV + PgBouncer are OPTIONAL/feature-flagged (off by default so they cannot destabilize the single-host stack). Real-data-or-honest-empty; no em/en dashes. This is WF-I (final source workflow) of a 9-workflow program.";

phase('Edge')
log('presigned route + gateway fix + k6 + cred cards')
const edge = (await parallel([
  () => agent(CTX + "\n\n=== I1: presigned upload route (NEW in apps/job-service public routes) ===\nGET /internal/public/jobs/:slug/upload-ticket?type=application/pdf -> returns { postURL, formData, objectKey } via MinIO presignedPostPolicy (reuse the resume-service S3 client + buildKey idea; bucket e.g. ats-incoming, key incoming/${tenantId}/${jobId}/${uuid}.<ext>, 5min expiry, contentType, contentLengthRange 1-10MB) so the browser uploads the resume DIRECTLY to MinIO. If the MinIO client/bucket is not available, return a clear 503 (the frontend falls back to the existing multipart apply — backward-compat). Mount under the existing /api/public gateway proxy (no gateway edit). In `contract` give the route + the ticket shape + the fallback.", { label: 'i1:presign', phase: 'Edge', schema: REPORT }),
  () => agent(CTX + "\n\n=== I5: gateway trust-proxy + rate-limit + keep-alive (EDIT api-gateway/src/app.ts + index.ts) ===\nTHE #1 THROUGHPUT BLOCKER FIX: (a) app.set('trust proxy', <hops/true-for-the-tunnel>) BEFORE the rate limiters so req.ip is the REAL client (without it every apply collapses into ONE rate-limit bucket -> instant 429 under load). (b) Move express-rate-limit to a shared Redis store (rate-limit-redis, reuse the existing ioredis at ~54) so limits are correct across replicas; keep a per-IP+email+job token-bucket (burst ~5, refill ~1/s) BUT raise the global ceiling well above legit peak so a real 5k spike is admitted (the async pipeline absorbs it) rather than 429'd; keep a DISABLE_RATE_LIMIT env escape for the load test. (c) shared keep-alive http.Agent (bounded maxSockets) for callService/forwardResume. (d) AbortSignal.timeout on the inter-service calls (match resume-service 3s). (e) server.keepAliveTimeout + headersTimeout in index.ts. If rate-limit-redis is not a dep, fall back to the in-memory store but STILL fix trust-proxy + the ceiling (note the dep). Backward-compat: existing routes unchanged except the limiter correctness. In `contract` give each fix + the env knobs (DISABLE_RATE_LIMIT, raised maxes).", { label: 'i5:gateway', phase: 'Edge', schema: REPORT }),
  () => agent(CTX + "\n\n=== I8: k6 load/stress harness (NEW load-tests/apply-custom.js + a small real PDF fixture) ===\nNEW load-tests/apply-custom.js (k6): OPEN-model ramping-arrival-rate executor (e.g. ramp 0->300 iters/s over 2m, hold 5m, spike to 600/s, drop), preAllocatedVUs 1000 / maxVUs 6000, discardResponseBodies:true. open() a small real PDF fixture in init context (binary), unique email per __VU/__ITER. Support BOTH apply paths via an env switch: APPLY_MODE=multipart uses http.file() multipart POST to /api/public/jobs/:slug/apply-custom (the existing path); APPLY_MODE=presigned does the 2-step (GET upload-ticket -> POST file to MinIO postURL -> POST apply JSON with objectKey). Thresholds (CI-failing): http_req_failed<0.01, http_req_duration p95<800 / p99<2000, a custom apply_submit_duration trend p95<1500, dropped_iterations<100. Parameterize BASE_URL, SLUG, TENANT via env. Also create load-tests/README.md documenting how to run it inside a Linux container/WSL2 (ulimit -n 250000) with DISABLE_RATE_LIMIT=1 + raised maxes, and the HONEST single-host caveat. In `contract` give the script's env knobs + thresholds + how to run.", { label: 'i8:k6', phase: 'Edge', schema: REPORT }),
  () => agent(CTX + "\n\n=== I7: per-board credential cards (EDIT apps/frontend settings/integrations) ===\nAdd per-hiring-board 'connect your <board> partner credentials' cards (indeed/linkedin/ziprecruiter/seek/naukri/dice/adzuna/jooble/wellfound/foundit/shine + google-jobs) to the integrations settings UI, reusing the EXISTING HackerRank/Codility assessment-provider card pattern: a card per board showing its status (CONNECTED when creds present, PENDING_PARTNER_APPROVAL for the partner-gated ones, AVAILABLE for the zero-gating feed ones like jooble/google-jobs), an honest 'requires partner approval / paid subscription' note where applicable, and a form to save creds via the existing /api/integrations CRUD (write-only secret fields, never display a saved secret). Only show when the job-distribution module is enabled (use-modules). In `contract` give the card set + statuses + the masking.", { label: 'i7:cards', phase: 'Edge', schema: REPORT }),
])).filter(Boolean)
log('Edge done: ' + edge.length + '/4')

phase('Pipeline')
log('accept-fast apply (both paths) + workers + status + frontend + infra')
const pipe = (await parallel([
  () => agent(CTX + "\n\n=== I2: accept-fast apply (EDIT apps/job-service/src/routes/public.ts apply-custom) — BACKWARD-COMPATIBLE ===\nMake apply-custom handle BOTH: (1) EXISTING multipart upload -> keep the CURRENT behavior so the frozen v1 + current v2 frontends are UNAFFECTED (do not change its response contract); optionally enqueue the heavy work async but the old client must still get its expected response. (2) NEW accept-fast JSON path: when the body carries a presigned { resume:{objectKey,filename,contentType,size} } -> Zod-validate fields (+ optional Turnstile token), statObject(objectKey) to verify size (never trust the client), ApplicationIdempotency upsert (UNIQUE(tenantId,idempotencyKey) where key = Idempotency-Key header or sha256(tenantId|slug|email|objectKey); locked->409, finished->replay the cached 202), ONE minimal Candidate+Application write (status PENDING_INGEST) in an interactive transaction, enqueue an 'apply-ingest' BullMQ job {applicationId,tenantId,objectKey}, return 202 { applicationId, statusUrl }. Stays on prismaAdmin. De-hot-spot the per-apply applicationCount UPDATE (drop it / make it a periodic rollup) so it is not a lock under load. In `contract` give the dual-path detection + the 202 shape + idempotency behavior.", { label: 'i2:applyfast', phase: 'Pipeline', schema: REPORT }),
  () => agent(CTX + "\n\n=== I3: async pipeline workers (NEW apps/job-service/src/workers/apply-ingest.worker.ts) ===\nBullMQ apply-ingest worker (clone the job/assessment worker boot; start in the service index): consumes {applicationId,tenantId,objectKey} -> (optional resume-scan step: IF CLAMAV_ENABLED env is set, scan via the clamav sidecar + quarantine; else skip straight through) -> move/reference the object from ats-incoming to the resume pipeline -> forward to resume-service parse -> screening (reuse the existing forward path; the worker sets tenant context from objectKey/job.data, NO multer so the async-context gotcha is gone) -> advance the Application status PENDING_INGEST -> SCANNED -> PARSED -> SCREENED. Idempotent per applicationId. Add the enqueue helper + queue name to a job-service queue lib. CLAMAV_ENABLED defaults OFF so the pipeline works without the sidecar. In `contract` give the job shape + queue name + the status progression + the CLAMAV_ENABLED gate.", { label: 'i3:workers', phase: 'Pipeline', schema: REPORT }),
  () => agent(CTX + "\n\n=== I4: status route + frontend 2-step (NEW status route + EDIT apps/frontend apply page) ===\nNEW GET /internal/public/applications/:id/status -> { status:'PENDING_INGEST'|'SCANNED'|'PARSED'|'SCREENED'|'REJECTED'|'RECEIVED' } (mounted under /api/public). EDIT the candidate-portal apply page (app/(candidate-portal)/jobs/[id]/apply/page.tsx) to PREFER the new fast path: GET upload-ticket -> POST file to MinIO -> POST apply JSON with objectKey + Idempotency-Key (+ Turnstile if configured) -> on 202 poll the statusUrl and show progress; FALL BACK to the existing multipart submit if upload-ticket returns 503 (so it always works). Keep the page resilient + honest. (This frontend change ships in the NEW v2 image only; the frozen v1 keeps the old multipart path, which I2 preserved.) In `contract` give the status route + the 2-step-with-fallback flow.", { label: 'i4:status-fe', phase: 'Pipeline', schema: REPORT }),
  () => agent(CTX + "\n\n=== I6: infra tuning (EDIT docker-compose.demo.yml + Prisma pool) — OPTIONAL services OFF by default ===\nEDIT docker-compose.demo.yml ADDITIVELY: (a) a Postgres command override raising max_connections (300-500), wal_buffers (16-64MB), max_wal_size (so bursts do not stall) — this is safe + always-on. (b) set a SMALL Prisma connection_limit (5-10) on the job-service DATABASE_URL(s) so it does not exhaust Postgres. (c) add a clamav sidecar service (clamav/clamav:stable) + a pgbouncer service, BOTH commented/profiled so they are NOT started by default (the app works without them; CLAMAV_ENABLED + a pgbouncer DATABASE_URL switch are opt-in for a production/perf run) — document that enabling PgBouncer requires the RLS-SET-LOCAL audit. Do NOT change the default service wiring in a way that breaks the running stack. In `contract` give the always-on tuning vs the opt-in services + the env switches.", { label: 'i6:infra', phase: 'Pipeline', schema: REPORT }),
])).filter(Boolean)
log('Pipeline done: ' + pipe.length + '/4')

return { edge, pipe }
